[env:seeed_wio_bg770a]
platform = https://github.com/SeeedJP/platform-nordicnrf52
platform_packages =
    framework-arduinoadafruitnrf52 @ https://github.com/SeeedJP/Adafruit_nRF52_Arduino.git
framework = arduino
board = seeed_wio_bg770a
build_flags =
    -DBOARD_VERSION_1_0
    -DCFG_LOGGER=3
lib_archive = no
lib_deps =
    seeedjp/WioCellular
    bblanchon/ArduinoJson @ ^7.4.3
monitor_speed = 115200
